version: '3.7'

services:
  jupyter:
    build:
        context: .
        dockerfile: ./training-notebook/Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=docker
    ports:
      - 8888:8888
      - 6006:6006
      - 6007:6007
      - 6008:6008

  server:
      image: tensorflow/serving
      networks:
        - uiNetwork 
      ports:
        - '8501:8501'
      volumes:
        - './models:/models'
      command:
        - '--rest_api_enable_cors_support=true'  # wont work w/ react if not set!

  reactapp:
    build:
      context: ./frontend
    networks:
      - uiNetwork  
    depends_on:
      - server
    ports:
      - 8080:80

    

networks:
  uiNetwork:
